baseURL = 'https://sogoddamntough.netlify.app/'
languageCode = 'en-us'
title = 'So Goddamn Tough'
theme = 'minimal'
outputs = { home = ["HTML"] }

[params]
description = 'Uplifting edits with phonk music'
author = 'You'
